//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOL2.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WOL2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please confirm the following action: {0} ähnelt.
        /// </summary>
        internal static string strConfirmAction {
            get {
                return ResourceManager.GetString("strConfirmAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A line in the CSV file is invalid. Continue anyway? ähnelt.
        /// </summary>
        internal static string strCSVLineNotValid {
            get {
                return ResourceManager.GetString("strCSVLineNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File saved as {0} ähnelt.
        /// </summary>
        internal static string strCsvSavedAs {
            get {
                return ResourceManager.GetString("strCsvSavedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (disconnected) ähnelt.
        /// </summary>
        internal static string strDisconnected {
            get {
                return ResourceManager.GetString("strDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please specify the new name. ähnelt.
        /// </summary>
        internal static string strEditGroup {
            get {
                return ResourceManager.GetString("strEditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Group ähnelt.
        /// </summary>
        internal static string strEditGroupTitle {
            get {
                return ResourceManager.GetString("strEditGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comment: ähnelt.
        /// </summary>
        internal static string strEditHostListComment {
            get {
                return ResourceManager.GetString("strEditHostListComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change Host-List Comment ähnelt.
        /// </summary>
        internal static string strEditHostListCommentTitle {
            get {
                return ResourceManager.GetString("strEditHostListCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit reboot timer for group  {0} ähnelt.
        /// </summary>
        internal static string strEditRebootTimerForGroup {
            get {
                return ResourceManager.GetString("strEditRebootTimerForGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit reboot timer for host {0} ähnelt.
        /// </summary>
        internal static string strEditRebootTimerForHost {
            get {
                return ResourceManager.GetString("strEditRebootTimerForHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit shutdown timer for group {0} ähnelt.
        /// </summary>
        internal static string strEditShutdownTimerForGroup {
            get {
                return ResourceManager.GetString("strEditShutdownTimerForGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit shutdown timer for host {0} ähnelt.
        /// </summary>
        internal static string strEditShutdownTimerForHost {
            get {
                return ResourceManager.GetString("strEditShutdownTimerForHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit timer for group {0} ähnelt.
        /// </summary>
        internal static string strEditTimerForGroup {
            get {
                return ResourceManager.GetString("strEditTimerForGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit wake timer for host {0} ähnelt.
        /// </summary>
        internal static string strEditTimerForHost {
            get {
                return ResourceManager.GetString("strEditTimerForHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string strError {
            get {
                return ResourceManager.GetString("strError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File opened. {0} hosts loaded. ähnelt.
        /// </summary>
        internal static string strFileOpened {
            get {
                return ResourceManager.GetString("strFileOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File successfully saved. ähnelt.
        /// </summary>
        internal static string strFileSaved {
            get {
                return ResourceManager.GetString("strFileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The help files (ReadMe_En.htm) could not be found. ähnelt.
        /// </summary>
        internal static string strHelpFileMissing {
            get {
                return ResourceManager.GetString("strHelpFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ReadMe_En.htm ähnelt.
        /// </summary>
        internal static string strHelpFileName {
            get {
                return ResourceManager.GetString("strHelpFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The host name is invalid. ähnelt.
        /// </summary>
        internal static string strHostnameInValid {
            get {
                return ResourceManager.GetString("strHostnameInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ths host name is valid. ähnelt.
        /// </summary>
        internal static string strHostnameValid {
            get {
                return ResourceManager.GetString("strHostnameValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logging will be enabled / disabled after WOL2 restart. ähnelt.
        /// </summary>
        internal static string strLoggingAfterRestart {
            get {
                return ResourceManager.GetString("strLoggingAfterRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This action requires a valid MAC address. ähnelt.
        /// </summary>
        internal static string strNeedMacAdressForThat {
            get {
                return ResourceManager.GetString("strNeedMacAdressForThat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Network scan finished. {0} hosts added. ähnelt.
        /// </summary>
        internal static string strNetworkScanFinished {
            get {
                return ResourceManager.GetString("strNetworkScanFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Network scan finished to {0}%. ähnelt.
        /// </summary>
        internal static string strNetworkScanProgress {
            get {
                return ResourceManager.GetString("strNetworkScanProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Network scan started. Please wait... ähnelt.
        /// </summary>
        internal static string strNetworkScanStarted {
            get {
                return ResourceManager.GetString("strNetworkScanStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please specify the name of the new group. ähnelt.
        /// </summary>
        internal static string strNewGroup {
            get {
                return ResourceManager.GetString("strNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new Group ähnelt.
        /// </summary>
        internal static string strNewGroupTitle {
            get {
                return ResourceManager.GetString("strNewGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No supported networks found ähnelt.
        /// </summary>
        internal static string strNoNetworksFound {
            get {
                return ResourceManager.GetString("strNoNetworksFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No timer set up. ähnelt.
        /// </summary>
        internal static string strNoTimer {
            get {
                return ResourceManager.GetString("strNoTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You are using the latest version of WOL2. ähnelt.
        /// </summary>
        internal static string strNoUpdateFound {
            get {
                return ResourceManager.GetString("strNoUpdateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die offline ähnelt.
        /// </summary>
        internal static string strOffline {
            get {
                return ResourceManager.GetString("strOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die online ähnelt.
        /// </summary>
        internal static string strOnline {
            get {
                return ResourceManager.GetString("strOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file name is reserved. Please use another file name to save the host list. ähnelt.
        /// </summary>
        internal static string strOverwriteProfile {
            get {
                return ResourceManager.GetString("strOverwriteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the name of the group you wish to remove ähnelt.
        /// </summary>
        internal static string strRemoveGroup {
            get {
                return ResourceManager.GetString("strRemoveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Group ähnelt.
        /// </summary>
        internal static string strRemoveGroupTitle {
            get {
                return ResourceManager.GetString("strRemoveGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The hosts file was changed. Do you want to save the changes? ähnelt.
        /// </summary>
        internal static string strSaveChangedFile {
            get {
                return ResourceManager.GetString("strSaveChangedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the SecureOn password. ähnelt.
        /// </summary>
        internal static string strSecureOnPrompt {
            get {
                return ResourceManager.GetString("strSecureOnPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send reboot signal to all members of group {0}. ähnelt.
        /// </summary>
        internal static string strSendRebootSignal {
            get {
                return ResourceManager.GetString("strSendRebootSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send shutdown signal to all members of group {0}. ähnelt.
        /// </summary>
        internal static string strSendShutdownSignal {
            get {
                return ResourceManager.GetString("strSendShutdownSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send WOL package to host {0}. ähnelt.
        /// </summary>
        internal static string strSendWolPackageToHost {
            get {
                return ResourceManager.GetString("strSendWolPackageToHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send WOL package to all members of group {0}. ähnelt.
        /// </summary>
        internal static string strSendWOLSignal {
            get {
                return ResourceManager.GetString("strSendWOLSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die starting ähnelt.
        /// </summary>
        internal static string strStarting {
            get {
                return ResourceManager.GetString("strStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; is now {1}. ähnelt.
        /// </summary>
        internal static string strStateChanged {
            get {
                return ResourceManager.GetString("strStateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thank you for using the Wake On Lan Tool 2.\n\nThe author would like to know more about its users and their contentment. Do you have 5 minutes to take part in a short survey (5 questions)?\n\n*Yes* = Opens the survey\n*No* = Do not ask again.\n*Cancel* = Ask me the next time. ähnelt.
        /// </summary>
        internal static string strSurveyText {
            get {
                return ResourceManager.GetString("strSurveyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WOL2 - Users survey ähnelt.
        /// </summary>
        internal static string strSurveyTitle {
            get {
                return ResourceManager.GetString("strSurveyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The timer ist disabled. ähnelt.
        /// </summary>
        internal static string strTimerIsDisabled {
            get {
                return ResourceManager.GetString("strTimerIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The timer is set up for:  ähnelt.
        /// </summary>
        internal static string strTimerSetup {
            get {
                return ResourceManager.GetString("strTimerSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die unknown ähnelt.
        /// </summary>
        internal static string strUnknown {
            get {
                return ResourceManager.GetString("strUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Online update... ähnelt.
        /// </summary>
        internal static string strUpdateTitle {
            get {
                return ResourceManager.GetString("strUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning: this action will delte the currently used XML profile (not the hosts file) and save all settings to the windows registry. Press OK to continue. ähnelt.
        /// </summary>
        internal static string strWarnDropProfile {
            get {
                return ResourceManager.GetString("strWarnDropProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome to the Wake On Lan Tool 2. ähnelt.
        /// </summary>
        internal static string strWelcome {
            get {
                return ResourceManager.GetString("strWelcome", resourceCulture);
            }
        }
    }
}
